using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ryn.Callbacks.Generator;

internal static class Emitter
{
    public static string? Emit(CallbackGroup group, SourceProductionContext context)
    {
        if (!Validate(group, context))
            return null;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        if (group.Namespace is not null)
        {
            source.Append("namespace ").Append(group.Namespace).AppendLine(";");
            source.AppendLine();
        }

        EmitRouter(source, group);
        source.AppendLine();
        EmitRegistrationExtension(source, group);
        return source.ToString();
    }

    private static bool Validate(CallbackGroup group, SourceProductionContext context)
    {
        var valid = true;
        var seenKinds = new HashSet<CallbackKind>();

        foreach (var callback in group.Callbacks)
        {
            if (callback.Problem != CallbackProblem.None)
            {
                ReportProblem(context, callback);
                valid = false;
                continue;
            }

            if (!seenKinds.Add(callback.Kind))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateCallbackKind,
                    callback.Location.ToLocation(),
                    group.TypeFullName,
                    CallbackKindName(callback.Kind)));
                valid = false;
            }
        }

        return valid;
    }

    private static void ReportProblem(SourceProductionContext context, CallbackInfo callback)
    {
        var location = callback.Location.ToLocation();
        switch (callback.Problem)
        {
            case CallbackProblem.InvalidContainingType:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidContainingType,
                    location,
                    callback.ContainingTypeFullName,
                    callback.ContainingTypeProblemReason));
                break;
            case CallbackProblem.InaccessibleMethod:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MethodMustBeAccessible,
                    location,
                    callback.MethodName));
                break;
            case CallbackProblem.GenericMethod:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.GenericMethod,
                    location,
                    callback.MethodName));
                break;
            case CallbackProblem.AsyncMethod:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.AsyncMethod,
                    location,
                    callback.MethodName));
                break;
            case CallbackProblem.InvalidParameter:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidParameter,
                    location,
                    CallbackKindName(callback.Kind),
                    callback.MethodName,
                    ExpectedParameterType(callback.Kind)));
                break;
            case CallbackProblem.InvalidReturn:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidReturnType,
                    location,
                    CallbackKindName(callback.Kind),
                    callback.MethodName,
                    ExpectedReturnType(callback.Kind)));
                break;
            case CallbackProblem.UnsupportedKind:
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.UnsupportedCallbackKind,
                    location,
                    callback.MethodName,
                    callback.KindDisplay));
                break;
        }
    }

    private static void EmitRouter(StringBuilder source, CallbackGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var navigating = Find(group, CallbackKind.WebViewNavigating);
        var navigated = Find(group, CallbackKind.WebViewNavigated);

        source.Append("file sealed class ").Append(routerName)
            .AppendLine(" : global::Ryn.Callbacks.IRynCallbackRouter");
        source.AppendLine("{");
        source.AppendLine("    public global::Ryn.Core.NavigationDecision OnWebViewNavigating(");
        source.AppendLine("        global::Ryn.Core.WebViewNavigatingContext context,");
        source.AppendLine("        global::System.IServiceProvider services)");
        source.AppendLine("    {");
        if (navigating is { } navigatingCallback)
        {
            source.Append("        return ")
                .Append(InvocationTarget(group, navigatingCallback))
                .Append(".@").Append(navigatingCallback.MethodName)
                .AppendLine("(context);");
        }
        else
        {
            source.AppendLine("        return global::Ryn.Core.NavigationDecision.Allow;");
        }
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public void OnWebViewNavigated(");
        source.AppendLine("        global::Ryn.Core.WebViewNavigatedContext context,");
        source.AppendLine("        global::System.IServiceProvider services)");
        source.AppendLine("    {");
        if (navigated is { } navigatedCallback)
        {
            source.Append("        ")
                .Append(InvocationTarget(group, navigatedCallback))
                .Append(".@").Append(navigatedCallback.MethodName)
                .AppendLine("(context);");
        }
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static void EmitRegistrationExtension(StringBuilder source, CallbackGroup group)
    {
        var routerName = $"{group.TypeName}Router";
        var extensionName = $"{group.TypeName}RynExtensions";

        source.Append("public static class ").Append(extensionName).AppendLine();
        source.AppendLine("{");
        source.Append("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add")
            .Append(group.TypeName)
            .AppendLine("(");
        source.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("    {");
        source.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<")
            .Append("global::Ryn.Callbacks.IRynCallbackRouter, ")
            .Append(routerName)
            .AppendLine(">(services);");

        if (!group.IsStaticContainingType)
        {
            source.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<")
                .Append(group.TypeFullName)
                .AppendLine(">(services);");
        }

        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static CallbackInfo? Find(CallbackGroup group, CallbackKind kind)
    {
        foreach (var callback in group.Callbacks)
        {
            if (callback.Kind == kind)
                return callback;
        }

        return null;
    }

    private static string InvocationTarget(CallbackGroup group, CallbackInfo callback)
    {
        if (callback.IsStaticMethod)
            return group.TypeFullName;

        return "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions."
            + "GetRequiredService<" + group.TypeFullName + ">(services)";
    }

    private static string CallbackKindName(CallbackKind kind) => kind switch
    {
        CallbackKind.WebViewNavigating => "WebViewNavigating",
        CallbackKind.WebViewNavigated => "WebViewNavigated",
        _ => "Unknown",
    };

    private static string ExpectedParameterType(CallbackKind kind) => kind switch
    {
        CallbackKind.WebViewNavigating => "Ryn.Core.WebViewNavigatingContext",
        CallbackKind.WebViewNavigated => "Ryn.Core.WebViewNavigatedContext",
        _ => "a supported callback context",
    };

    private static string ExpectedReturnType(CallbackKind kind) => kind switch
    {
        CallbackKind.WebViewNavigating => "Ryn.Core.NavigationDecision",
        CallbackKind.WebViewNavigated => "void",
        _ => "a supported callback return type",
    };
}
